AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate CI/CD POC without EC2 and NGINX

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
  ContainerPort:
    Type: Number
    Default: 3000
  ActivityImageUrl:
    Type: String
  AttendanceImageUrl:
    Type: String

Resources:

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: cicd-poc-cluster

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: cicd-poc-alb
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !GetAtt ALBSecurityGroup.GroupId

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ActivityTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: cicd-p-ActivityTG
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /activity
      HealthCheckPort: traffic-port
      Matcher:
        HttpCode: 200

  AttendanceTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: cicd-p-AttendanceTG
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /attendance
      HealthCheckPort: traffic-port
      Matcher:
        HttpCode: 200

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 200
            ContentType: text/plain
            MessageBody: ALB running

  ActivityRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values: [/activity/*]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ActivityTG

  AttendanceRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref Listener
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values: [/attendance/*]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref AttendanceTG

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ActivityTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: activity-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: activity
          Image: !Ref ActivityImageUrl
          PortMappings:
            - ContainerPort: !Ref ContainerPort

  AttendanceTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: attendance-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: attendance
          Image: !Ref AttendanceImageUrl
          PortMappings:
            - ContainerPort: !Ref ContainerPort

  ActivityService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref ActivityTaskDef
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !GetAtt ALBSecurityGroup.GroupId
      LoadBalancers:
        - ContainerName: activity
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref ActivityTG

  AttendanceService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref AttendanceTaskDef
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1
            - !Ref PublicSubnet2
          SecurityGroups:
            - !GetAtt ALBSecurityGroup.GroupId
      LoadBalancers:
        - ContainerName: attendance
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref AttendanceTG

Outputs:
  ALBURL:
    Value: !Join ["", ["http://", !GetAtt ALB.DNSName]]
    Description: URL of the application load balancer